version: "0.2"
ignorePaths:
  - build/**
  - components/**
  - assessments/**
  - finopspp.egg-info/**
  - tools/scratch/**
  - pyproject.toml
words:
  - actuals
  - byol
  - collab
  - finopspp
  - gamify
  - itam
  - pbgc
  - prasshant
  - pydantic
  - pylint
  - pylintrc
  - pymarkdownlnt
  - pyml
  - pyproject
  - quigley
  - rarr
  - rcfile
  - secho
  - sharrma
  - sumif
  - venv
  - xlsxwriter
allowCompoundWords: true
